version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: catp-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Api/Dockerfile
    container_name: catp-api
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RabbitMq__HostName: rabbitmq
      RabbitMq__Port: 5672
      RabbitMq__UserName: rabbitmq
      RabbitMq__Password: rabbitmq
      RabbitMq__UseSsl: "false"
      RabbitMq__VHost: "/"
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
    ports:
      - "5073:80"
  simulator:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    container_name: catp-simulator
    volumes:
      - "..:/src:cached"
    working_dir: /src/simulator/CriticalAssetSimulator
    command: dotnet run --project CriticalAssetSimulator.csproj --configuration Release
    depends_on:
      rabbitmq:
        condition: service_healthy

  grafana:
    image: grafana/grafana:latest
    container_name: catp-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./Infrastructure/Monitoring/Dashboards/Grafana/provisioning:/etc/grafana/provisioning
      - ./Infrastructure/Monitoring/Dashboards/Grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    container_name: catp-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./Infrastructure/Monitoring/Metrics/Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - api
