name: CD

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          # context: ./backend
          context: .
          file: backend/Api/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/backend:latest
            ghcr.io/${{ github.repository }}/backend:${{ github.sha }}
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          # context: ./frontend/critical-asset-frontend
          context: .
          file: frontend/critical-asset-frontend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/frontend:latest,ghcr.io/${{ github.repository }}/frontend:${{ github.sha }}

      - name: Build and push simulator image
        uses: docker/build-push-action@v5
        with:
          # context: ./simulator/CriticalAssetSimulator
          context: .
          file: simulator/CriticalAssetSimulator/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/simulator:latest,ghcr.io/${{ github.repository }}/simulator:${{ github.sha }}
